apiVersion: v1
kind: Service
metadata:
  name: keycloak
spec:
  selector:
    app: keycloak
  ports:
    - protocol: TCP
      port: 8484
      targetPort: 8080
  type: LoadBalancer  # Или NodePort, в зависимости от вашей конфигурации